// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IBi:caretDown': typeof import('~icons/bi/caret-down')['default']
    'IBi:caretUp': typeof import('~icons/bi/caret-up')['default']
    'ICil:mediaPlay': typeof import('~icons/cil/media-play')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    'IFileIcons:configPython': typeof import('~icons/file-icons/config-python')['default']
    'IFileIcons:testPython': typeof import('~icons/file-icons/test-python')['default']
    'IMdi:languagePython': typeof import('~icons/mdi/language-python')['default']
    TheApirefSidebar: typeof import('./src/components/TheApirefSidebar.vue')['default']
    TheExamplesSidebar: typeof import('./src/components/TheExamplesSidebar.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}

export { }
