// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IFaBrands:github': typeof import('~icons/fa-brands/github')['default']
    'IFaSolid:moon': typeof import('~icons/fa-solid/moon')['default']
    'IFaSolid:sun': typeof import('~icons/fa-solid/sun')['default']
    'IPh:caretDownBold': typeof import('~icons/ph/caret-down-bold')['default']
    'IPh:caretRightBold': typeof import('~icons/ph/caret-right-bold')['default']
    TheApirefSidebar: typeof import('./src/components/TheApirefSidebar.vue')['default']
    TheExamplesSidebar: typeof import('./src/components/TheExamplesSidebar.vue')['default']
    TheHeader: typeof import('./src/components/TheHeader.vue')['default']
    TheSidebar: typeof import('./src/components/TheSidebar.vue')['default']
  }
}

export { }
