name: 'coverage'
on:
    pull_request:
        branches:
            - master
            - main
jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Get Coverage
            uses: orgoro/coverage@v3
            with:
                coverageFile: ./coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}