on: ["push", "pull_request"]

name: Test Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Coveralls
      uses: coverallsapp/github-action@v1
      with:
            path-to-lcov: ./coverage.lcov
            token: ${{ secrets.GITHUB_TOKEN }}